# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Document(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, photo_urls=None, status=None):  # noqa: E501
        """Document - a model defined in OpenAPI

        :param id: The id of this Document.  # noqa: E501
        :type id: int
        :param name: The name of this Document.  # noqa: E501
        :type name: str
        :param photo_urls: The photo_urls of this Document.  # noqa: E501
        :type photo_urls: List[str]
        :param status: The status of this Document.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'photo_urls': List[str],
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'photo_urls': 'photoUrls',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._photo_urls = photo_urls
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Document':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Document of this Document.  # noqa: E501
        :rtype: Document
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Document.


        :return: The id of this Document.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Document.


        :param id: The id of this Document.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Document.


        :return: The name of this Document.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Document.


        :param name: The name of this Document.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def photo_urls(self):
        """Gets the photo_urls of this Document.


        :return: The photo_urls of this Document.
        :rtype: List[str]
        """
        return self._photo_urls

    @photo_urls.setter
    def photo_urls(self, photo_urls):
        """Sets the photo_urls of this Document.


        :param photo_urls: The photo_urls of this Document.
        :type photo_urls: List[str]
        """
        if photo_urls is None:
            raise ValueError("Invalid value for `photo_urls`, must not be `None`")  # noqa: E501

        self._photo_urls = photo_urls

    @property
    def status(self):
        """Gets the status of this Document.

        pet status in the store  # noqa: E501

        :return: The status of this Document.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Document.

        pet status in the store  # noqa: E501

        :param status: The status of this Document.
        :type status: str
        """
        allowed_values = ["available", "pending", "sold"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
